import random

def truth():
	options = ["What's the biggest lie you've told to somebody in this room?","What question would you least like to be asked?","Have you ever gone a day without underwear?","What is one thing about yourself you try to keep hidden?","Have you ever done something against the law?","When was the last time you peed in a swimming pool?","What's something you secretly like but are embarrassed by?","What's something about yourself that would scare other people if they knew?","Do you have a diary?","Have you ever watched an *adult film*?","Who is your favourite person in this room?","Who are your two least favourite people in this room?","When was the last time you wet your pants?","Have you ever pooped in your pants?","If you were the opposite sex for an hour, what would you do?","List all the things in your room that you have made some attempt to hide.","What's the worst thing you've ever done to your parents?","What's the most embarrassing thing you've been to the doctor for?","What's the most expensive thing you've broken?","What's the worst thing you've ever done to your siblings?","If you could be invisible for 2 hours, what would you do?","What's the most embarrassing song you like?","What's the most embarrassing TV show you like?","What's the most embarrassing website you like?","What's the most embarrassing movie you like?","What Was Your First Kiss Like?","What Is Your Least Favorite Thing About Your Best Friend?","Have You Ever Committed A Crime? If So, What Was It?","Have You Ever Cried From Watching A TV Show Or A Movie?"," What Do You Do When You Are Alone And No One Is Watching You?","What Is One Thing That You Have Always Wanted To Do But Have Not Gotten Around To It Yet?",'Who is the sexiest person in this room?','Who is your current crush?']
	question = random.choice(options)
	return question


def dare():
	options = ["Do a *show and tell* with the ENTIRE contents of your purse","Pick your nose and eat it in front of the group.",'''Text five people in your phone contacts list with the message "I'm awesome!"''',"Make a rap song about (insert topic) and perform it to the group.","Put an ice cube down your back.","Imitate another player and have everyone guess who you are.","Do an imitation of Tarzan.","Pick One Person In The Group, What Is Some Honest Relationship Advice You Would Give Them?","Tell Us About Your Five Bad Habits.","Do 50 sit ups.","Send a love letter to someone on Whatsapp(except the person playing the game).",'Send someone a message that says, “I know what you did last summer.”',"Say the alphabet backwards.","Call someone on your phone and talk to them for 5 minutes without telling them that you are playing Truth or Dare.","Prank call someone and pretend she/he is your girlfriend/boyfriend and propose to him/her.","Try to do a stand up comedy in front of the other players.","Show your whole browsing history to the players in the room.","Propose to the person under you in voice channel","Prank call someone and make them believe that they have won the lottery.","Prank call someone and tell them that you are horny.","Try to touch your nose with your tongue.","Call your closest friend and invite him/her for a threesome.","Make out with your hand.","Post an old selfie on your Instagram story.","Do 30 situps."]
	question = random.choice(options)
	return question